version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: 'routbisu/apollo-demo-server'
    ports:
      - 4000:4000
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: 'routbisu/apollo-demo-client'
    ports:
      - 3000:3000
